import { existsSync, readFileSync, writeFileSync, mkdirSync } from 'fs';
import { join } from 'path';
import { homedir } from 'os';
import { execSync, spawn } from 'child_process';
import {
  colors,
  bold,
  RESET,
  gradient,
  icons,
  writeLine,
  box,
  padEnd,
} from '../lib/terminal.js';

interface StackConfig {
  SQUADS_DATABASE_URL: string;
  SQUADS_BRIDGE_URL: string;
  LANGFUSE_HOST: string;
  LANGFUSE_PUBLIC_KEY: string;
  LANGFUSE_SECRET_KEY: string;
  REDIS_URL: string;
}

interface ContainerStatus {
  name: string;
  running: boolean;
  healthy: boolean;
  port?: string;
}

const DEFAULT_CONFIG: StackConfig = {
  SQUADS_DATABASE_URL: 'postgresql://user:password@localhost:5432/squads',
  SQUADS_BRIDGE_URL: 'http://localhost:8088',
  LANGFUSE_HOST: 'http://localhost:3100',
  LANGFUSE_PUBLIC_KEY: '',
  LANGFUSE_SECRET_KEY: '',
  REDIS_URL: 'redis://localhost:6379',
};

const CONFIG_PATH = join(homedir(), '.squadsrc');

/**
 * Load config from ~/.squadsrc
 */
export function loadStackConfig(): Partial<StackConfig> | null {
  if (!existsSync(CONFIG_PATH)) {
    return null;
  }

  try {
    const content = readFileSync(CONFIG_PATH, 'utf-8');
    const config: Partial<StackConfig> = {};

    for (const line of content.split('\n')) {
      const trimmed = line.trim();
      if (!trimmed || trimmed.startsWith('#')) continue;

      const match = trimmed.match(/^export\s+(\w+)=["']?([^"'\n]*)["']?$/);
      if (match) {
        const [, key, value] = match;
        if (key in DEFAULT_CONFIG) {
          (config as Record<string, string>)[key] = value;
        }
      }
    }

    return config;
  } catch {
    return null;
  }
}

/**
 * Save config to ~/.squadsrc
 */
function saveStackConfig(config: StackConfig): void {
  const lines = [
    '# Squads CLI Local Stack Configuration',
    '# Generated by: squads stack init',
    `# Date: ${new Date().toISOString().split('T')[0]}`,
    '',
    '# Database',
    `export SQUADS_DATABASE_URL="${config.SQUADS_DATABASE_URL}"`,
    '',
    '# Bridge API',
    `export SQUADS_BRIDGE_URL="${config.SQUADS_BRIDGE_URL}"`,
    '',
    '# Langfuse',
    `export LANGFUSE_HOST="${config.LANGFUSE_HOST}"`,
    `export LANGFUSE_PUBLIC_KEY="${config.LANGFUSE_PUBLIC_KEY}"`,
    `export LANGFUSE_SECRET_KEY="${config.LANGFUSE_SECRET_KEY}"`,
    '',
    '# Redis',
    `export REDIS_URL="${config.REDIS_URL}"`,
    '',
    '# To activate: source ~/.squadsrc',
    '',
  ];

  writeFileSync(CONFIG_PATH, lines.join('\n'));
}

/**
 * Apply config to current process environment
 */
export function applyStackConfig(): void {
  const config = loadStackConfig();
  if (!config) return;

  for (const [key, value] of Object.entries(config)) {
    if (value && !process.env[key]) {
      process.env[key] = value;
    }
  }
}

/**
 * Check if Docker is running
 */
function isDockerRunning(): boolean {
  try {
    execSync('docker info', { stdio: 'ignore' });
    return true;
  } catch {
    return false;
  }
}

/**
 * Get container status
 */
function getContainerStatus(name: string): ContainerStatus {
  try {
    // First check if container is running
    const runningOutput = execSync(
      `docker inspect ${name} --format '{{.State.Running}}'`,
      { encoding: 'utf-8', stdio: ['pipe', 'pipe', 'ignore'] }
    ).trim();

    const running = runningOutput === 'true';

    if (!running) {
      return { name, running: false, healthy: false };
    }

    // Get port info
    let port: string | undefined;
    try {
      const portOutput = execSync(
        `docker inspect ${name} --format '{{range .NetworkSettings.Ports}}{{range .}}{{.HostPort}}{{end}}{{end}}'`,
        { encoding: 'utf-8', stdio: ['pipe', 'pipe', 'ignore'] }
      ).trim();
      port = portOutput || undefined;
    } catch {
      // Ignore port errors
    }

    // Check health status (may not exist for all containers)
    let healthy = true; // Default to healthy if running but no health check
    try {
      const healthOutput = execSync(
        `docker inspect ${name} --format '{{if .State.Health}}{{.State.Health.Status}}{{else}}none{{end}}'`,
        { encoding: 'utf-8', stdio: ['pipe', 'pipe', 'ignore'] }
      ).trim();

      if (healthOutput === 'healthy' || healthOutput === 'none') {
        healthy = true;
      } else if (healthOutput === 'starting') {
        healthy = false; // Starting means not yet healthy
      } else {
        healthy = false; // unhealthy or other states
      }
    } catch {
      // If health check fails, assume healthy if running
      healthy = true;
    }

    return { name, running, healthy, port };
  } catch {
    return { name, running: false, healthy: false };
  }
}

/**
 * Check service connectivity
 */
async function checkService(url: string, timeout = 2000): Promise<boolean> {
  try {
    const controller = new AbortController();
    const timeoutId = setTimeout(() => controller.abort(), timeout);

    const response = await fetch(url, { signal: controller.signal });
    clearTimeout(timeoutId);
    return response.ok;
  } catch {
    return false;
  }
}

/**
 * Get Langfuse API keys from the docker .env file
 */
function getLangfuseKeysFromDockerEnv(): { publicKey: string; secretKey: string } | null {
  const envPaths = [
    join(process.cwd(), 'docker', '.env'),
    join(process.cwd(), '..', 'squads-cli', 'docker', '.env'),
    join(homedir(), 'agents-squads', 'squads-cli', 'docker', '.env'),
  ];

  for (const envPath of envPaths) {
    if (existsSync(envPath)) {
      const content = readFileSync(envPath, 'utf-8');
      const publicMatch = content.match(/LANGFUSE_PUBLIC_KEY=(\S+)/);
      const secretMatch = content.match(/LANGFUSE_SECRET_KEY=(\S+)/);

      if (publicMatch && secretMatch) {
        return {
          publicKey: publicMatch[1],
          secretKey: secretMatch[1],
        };
      }
    }
  }

  return null;
}

/**
 * Find docker-compose directory
 */
function findDockerComposeDir(): string | null {
  const candidates = [
    join(process.cwd(), 'docker'),
    join(process.cwd(), '..', 'squads-cli', 'docker'),
    join(homedir(), 'agents-squads', 'squads-cli', 'docker'),
  ];

  for (const dir of candidates) {
    if (existsSync(join(dir, 'docker-compose.yml'))) {
      return dir;
    }
  }

  return null;
}

/**
 * squads stack init - detect and configure local stack
 */
export async function stackInitCommand(): Promise<void> {
  writeLine();
  writeLine(`  ${gradient('squads')} ${colors.dim}stack init${RESET}`);
  writeLine();

  // Check Docker
  if (!isDockerRunning()) {
    writeLine(`  ${colors.red}${icons.error}${RESET} Docker is not running`);
    writeLine(`  ${colors.dim}Start Docker Desktop and try again${RESET}`);
    writeLine();
    return;
  }

  writeLine(`  ${colors.green}${icons.success}${RESET} Docker is running`);

  // Check containers
  const containers = [
    'squads-postgres',
    'squads-redis',
    'squads-bridge',
    'squads-langfuse',
    'squads-otel-collector',
  ];

  const statuses = containers.map(getContainerStatus);
  const allRunning = statuses.every((s) => s.running);

  writeLine();
  writeLine(`  ${bold}Containers${RESET}`);

  for (const status of statuses) {
    const icon = status.running
      ? status.healthy
        ? `${colors.green}●${RESET}`
        : `${colors.yellow}●${RESET}`
      : `${colors.red}○${RESET}`;
    const portInfo = status.port ? `${colors.dim}:${status.port}${RESET}` : '';
    writeLine(`  ${icon} ${status.name}${portInfo}`);
  }

  if (!allRunning) {
    writeLine();
    writeLine(`  ${colors.yellow}${icons.warning}${RESET} Some containers not running`);
    writeLine(`  ${colors.dim}Run: squads stack up${RESET}`);
    writeLine();
    return;
  }

  // Get Langfuse keys
  const langfuseKeys = getLangfuseKeysFromDockerEnv();

  // Build config
  const config: StackConfig = {
    ...DEFAULT_CONFIG,
    LANGFUSE_PUBLIC_KEY: langfuseKeys?.publicKey || '',
    LANGFUSE_SECRET_KEY: langfuseKeys?.secretKey || '',
  };

  // Test connections
  writeLine();
  writeLine(`  ${bold}Testing connections${RESET}`);

  const bridgeOk = await checkService(`${config.SQUADS_BRIDGE_URL}/health`);
  const langfuseOk = await checkService(`${config.LANGFUSE_HOST}/api/public/health`);

  writeLine(
    `  ${bridgeOk ? colors.green + icons.success : colors.red + icons.error}${RESET} Bridge ${colors.dim}${config.SQUADS_BRIDGE_URL}${RESET}`
  );
  writeLine(
    `  ${langfuseOk ? colors.green + icons.success : colors.red + icons.error}${RESET} Langfuse ${colors.dim}${config.LANGFUSE_HOST}${RESET}`
  );

  // Save config
  saveStackConfig(config);

  writeLine();
  writeLine(`  ${colors.green}${icons.success}${RESET} Config saved to ${colors.cyan}~/.squadsrc${RESET}`);
  writeLine();
  writeLine(`  ${colors.dim}To activate in current shell:${RESET}`);
  writeLine(`  ${colors.cyan}source ~/.squadsrc${RESET}`);
  writeLine();
  writeLine(`  ${colors.dim}Or add to your ~/.zshrc:${RESET}`);
  writeLine(`  ${colors.cyan}[ -f ~/.squadsrc ] && source ~/.squadsrc${RESET}`);
  writeLine();
}

/**
 * squads stack status - show connection health
 */
export async function stackStatusCommand(): Promise<void> {
  writeLine();
  writeLine(`  ${gradient('squads')} ${colors.dim}stack status${RESET}`);
  writeLine();

  // Check Docker
  if (!isDockerRunning()) {
    writeLine(`  ${colors.red}${icons.error}${RESET} Docker is not running`);
    writeLine();
    return;
  }

  // Container status
  const containers = [
    { name: 'squads-postgres', service: 'Database' },
    { name: 'squads-redis', service: 'Cache' },
    { name: 'squads-bridge', service: 'Bridge API' },
    { name: 'squads-langfuse', service: 'Langfuse' },
    { name: 'squads-otel-collector', service: 'Telemetry' },
  ];

  const w = { service: 12, container: 22, status: 12 };
  const tableWidth = w.service + w.container + w.status + 6;

  writeLine(`  ${colors.purple}${box.topLeft}${colors.dim}${box.horizontal.repeat(tableWidth)}${colors.purple}${box.topRight}${RESET}`);
  writeLine(
    `  ${colors.purple}${box.vertical}${RESET} ${bold}${padEnd('SERVICE', w.service)}${RESET}${bold}${padEnd('CONTAINER', w.container)}${RESET}${bold}STATUS${RESET}      ${colors.purple}${box.vertical}${RESET}`
  );
  writeLine(`  ${colors.purple}${box.teeRight}${colors.dim}${box.horizontal.repeat(tableWidth)}${colors.purple}${box.teeLeft}${RESET}`);

  for (const { name, service } of containers) {
    const status = getContainerStatus(name);
    const statusIcon = status.running
      ? status.healthy
        ? `${colors.green}● healthy${RESET}`
        : `${colors.yellow}● starting${RESET}`
      : `${colors.red}○ stopped${RESET}`;

    writeLine(
      `  ${colors.purple}${box.vertical}${RESET} ${colors.cyan}${padEnd(service, w.service)}${RESET}${colors.dim}${padEnd(name, w.container)}${RESET}${statusIcon}  ${colors.purple}${box.vertical}${RESET}`
    );
  }

  writeLine(`  ${colors.purple}${box.bottomLeft}${colors.dim}${box.horizontal.repeat(tableWidth)}${colors.purple}${box.bottomRight}${RESET}`);

  // Config status
  writeLine();
  const config = loadStackConfig();
  if (config) {
    writeLine(`  ${colors.green}${icons.success}${RESET} Config loaded from ${colors.cyan}~/.squadsrc${RESET}`);

    // Check if env vars are set
    const envVars = ['SQUADS_DATABASE_URL', 'SQUADS_BRIDGE_URL', 'LANGFUSE_HOST'];
    const missing = envVars.filter((v) => !process.env[v]);

    if (missing.length > 0) {
      writeLine(`  ${colors.yellow}${icons.warning}${RESET} Env vars not in shell: ${colors.dim}${missing.join(', ')}${RESET}`);
      writeLine(`  ${colors.dim}Run: source ~/.squadsrc${RESET}`);
    } else {
      writeLine(`  ${colors.green}${icons.success}${RESET} All env vars loaded`);
    }
  } else {
    writeLine(`  ${colors.yellow}${icons.warning}${RESET} No config found`);
    writeLine(`  ${colors.dim}Run: squads stack init${RESET}`);
  }

  writeLine();
}

/**
 * squads stack env - print export commands
 */
export function stackEnvCommand(): void {
  const config = loadStackConfig();

  if (!config) {
    // Output defaults if no config
    console.log(`# Squads Local Stack - Default Config`);
    console.log(`# Run 'squads stack init' to auto-detect and save`);
    console.log();
    for (const [key, value] of Object.entries(DEFAULT_CONFIG)) {
      console.log(`export ${key}="${value}"`);
    }
    return;
  }

  // Output saved config
  console.log(`# Squads Local Stack Config`);
  console.log(`# From: ~/.squadsrc`);
  console.log();
  for (const [key, value] of Object.entries(config)) {
    console.log(`export ${key}="${value}"`);
  }
}

/**
 * squads stack up - start docker compose
 */
export async function stackUpCommand(): Promise<void> {
  writeLine();
  writeLine(`  ${gradient('squads')} ${colors.dim}stack up${RESET}`);
  writeLine();

  const composeDir = findDockerComposeDir();

  if (!composeDir) {
    writeLine(`  ${colors.red}${icons.error}${RESET} docker-compose.yml not found`);
    writeLine();
    writeLine(`  ${colors.dim}Expected locations:${RESET}`);
    writeLine(`  ${colors.dim}  ./docker/docker-compose.yml${RESET}`);
    writeLine(`  ${colors.dim}  ~/agents-squads/squads-cli/docker/docker-compose.yml${RESET}`);
    writeLine();
    return;
  }

  writeLine(`  ${colors.cyan}${icons.progress}${RESET} Starting containers from ${colors.dim}${composeDir}${RESET}`);
  writeLine();

  try {
    const child = spawn('docker-compose', ['up', '-d'], {
      cwd: composeDir,
      stdio: 'inherit',
    });

    await new Promise<void>((resolve, reject) => {
      child.on('close', (code) => {
        if (code === 0) resolve();
        else reject(new Error(`docker-compose exited with code ${code}`));
      });
      child.on('error', reject);
    });

    writeLine();
    writeLine(`  ${colors.green}${icons.success}${RESET} Stack started`);
    writeLine(`  ${colors.dim}Run: squads stack init${RESET} to configure CLI`);
    writeLine();
  } catch (error) {
    writeLine(`  ${colors.red}${icons.error}${RESET} Failed to start stack`);
    writeLine(`  ${colors.dim}${error}${RESET}`);
    writeLine();
  }
}

/**
 * squads stack health - comprehensive health check with diagnostics
 */
export async function stackHealthCommand(verbose = false): Promise<void> {
  writeLine();
  writeLine(`  ${gradient('squads')} ${colors.dim}stack health${RESET}`);
  writeLine();

  // Check Docker
  if (!isDockerRunning()) {
    writeLine(`  ${colors.red}${icons.error}${RESET} Docker is not running`);
    writeLine();
    process.exitCode = 1;
    return;
  }

  // All containers including engram stack
  const containers = [
    { name: 'squads-postgres', service: 'postgres', healthUrl: '', critical: true },
    { name: 'squads-redis', service: 'redis', healthUrl: '', critical: true },
    { name: 'squads-neo4j', service: 'neo4j', healthUrl: 'http://localhost:7474', critical: false },
    { name: 'squads-bridge', service: 'bridge', healthUrl: 'http://localhost:8088/health', critical: true },
    { name: 'squads-otel-collector', service: 'otel', healthUrl: '', critical: false },
    { name: 'squads-langfuse', service: 'langfuse', healthUrl: 'http://localhost:3100/api/public/health', critical: false },
    { name: 'squads-mem0', service: 'mem0', healthUrl: 'http://localhost:8000/health', critical: false },
    { name: 'squads-engram-mcp', service: 'engram', healthUrl: 'http://localhost:8080/', critical: false },
  ];

  let hasFailures = false;
  const results: Array<{ name: string; service: string; ok: boolean; status: string; logs?: string }> = [];

  for (const container of containers) {
    const status = getContainerStatus(container.name);
    let ok = status.running && status.healthy;
    let statusText = '';

    if (!status.running) {
      statusText = 'stopped';
      ok = false;
    } else if (!status.healthy) {
      statusText = 'unhealthy';
      ok = false;
    } else if (container.healthUrl) {
      // Additional HTTP health check
      const httpOk = await checkService(container.healthUrl);
      if (!httpOk) {
        statusText = 'not responding';
        ok = false;
      } else {
        statusText = 'healthy';
      }
    } else {
      statusText = 'healthy';
    }

    // Get logs if unhealthy
    let logs: string | undefined;
    if (!ok && verbose) {
      try {
        logs = execSync(`docker logs ${container.name} --tail 10 2>&1`, {
          encoding: 'utf-8',
          stdio: ['pipe', 'pipe', 'pipe'],
        });
      } catch {
        logs = '(no logs available)';
      }
    }

    if (!ok && container.critical) {
      hasFailures = true;
    }

    results.push({ name: container.name, service: container.service, ok, status: statusText, logs });
  }

  // Display results
  for (const r of results) {
    const icon = r.ok ? `${colors.green}✓${RESET}` : `${colors.red}✗${RESET}`;
    const statusColor = r.ok ? colors.green : colors.red;
    writeLine(`  ${icon} ${padEnd(r.service, 10)} ${statusColor}${r.status}${RESET}`);

    if (r.logs && !r.ok) {
      writeLine(`    ${colors.dim}${'-'.repeat(40)}${RESET}`);
      for (const line of r.logs.split('\n').slice(0, 5)) {
        writeLine(`    ${colors.dim}${line.substring(0, 70)}${RESET}`);
      }
    }
  }

  writeLine();

  // Summary
  const healthy = results.filter((r) => r.ok).length;
  const total = results.length;

  if (hasFailures) {
    writeLine(`  ${colors.red}${icons.error}${RESET} ${healthy}/${total} services healthy - critical failures`);
    writeLine(`  ${colors.dim}Run with -v for logs: squads stack health -v${RESET}`);
    process.exitCode = 1;
  } else if (healthy < total) {
    writeLine(`  ${colors.yellow}${icons.warning}${RESET} ${healthy}/${total} services healthy - non-critical issues`);
  } else {
    writeLine(`  ${colors.green}${icons.success}${RESET} ${healthy}/${total} services healthy`);
  }

  writeLine();
}

/**
 * squads stack logs - show logs for a specific service
 */
export function stackLogsCommand(service: string, tail = 50): void {
  const containerMap: Record<string, string> = {
    postgres: 'squads-postgres',
    redis: 'squads-redis',
    neo4j: 'squads-neo4j',
    bridge: 'squads-bridge',
    otel: 'squads-otel-collector',
    langfuse: 'squads-langfuse',
    mem0: 'squads-mem0',
    engram: 'squads-engram-mcp',
  };

  const container = containerMap[service] || `squads-${service}`;

  try {
    execSync(`docker logs ${container} --tail ${tail}`, { stdio: 'inherit' });
  } catch {
    writeLine(`  ${colors.red}${icons.error}${RESET} Container ${container} not found`);
  }
}

/**
 * squads stack down - stop docker compose
 */
export async function stackDownCommand(): Promise<void> {
  writeLine();
  writeLine(`  ${gradient('squads')} ${colors.dim}stack down${RESET}`);
  writeLine();

  const composeDir = findDockerComposeDir();

  if (!composeDir) {
    writeLine(`  ${colors.red}${icons.error}${RESET} docker-compose.yml not found`);
    writeLine();
    return;
  }

  writeLine(`  ${colors.cyan}${icons.progress}${RESET} Stopping containers...`);
  writeLine();

  try {
    const child = spawn('docker-compose', ['down'], {
      cwd: composeDir,
      stdio: 'inherit',
    });

    await new Promise<void>((resolve, reject) => {
      child.on('close', (code) => {
        if (code === 0) resolve();
        else reject(new Error(`docker-compose exited with code ${code}`));
      });
      child.on('error', reject);
    });

    writeLine();
    writeLine(`  ${colors.green}${icons.success}${RESET} Stack stopped`);
    writeLine();
  } catch (error) {
    writeLine(`  ${colors.red}${icons.error}${RESET} Failed to stop stack`);
    writeLine(`  ${colors.dim}${error}${RESET}`);
    writeLine();
  }
}
